#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — Cloudflare R2 provisioning for the Yufa ToS Classic launcher.
# Run from the repo root:  bash scripts/r2-setup.sh
# Re-runnable: values already in .env are offered as defaults.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

BUCKET="yufa-patch"
CONFIG_FILES=(
  "publish.config.json"
  "packages/launcher/src/main/constants.ts"
  "packages/launcher/electron-builder.yml"
)

# Sanity: run from the repo root, curl available for the Range check.
if [[ ! -f publish.config.json || ! -d packages/launcher ]]; then
  printf '%sRun this from the repo root (where publish.config.json lives).%s\n' "$RED" "$RESET"
  exit 1
fi
command -v curl >/dev/null 2>&1 || { printf '%scurl is required for stage 7.%s\n' "$RED" "$RESET"; exit 1; }

banner "Cloudflare R2 — go-live provisioning"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — Account ID"
say "The publish CLI talks to R2 through the S3 endpoint"
say "https://<account id>.r2.cloudflarestorage.com — we need that account id."
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Pick the account that owns the game's domain, if asked."
step "On R2 Object Storage → Overview, look at the right-hand sidebar:"
step "'Account details' → 'Account ID' → click the copy icon (32 hex chars)."
note "If the sidebar is missing, the same id is on any zone's Overview page."
while :; do
  ask R2_ACCOUNT_ID "Paste the Account ID:"
  [[ "$R2_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]] && break
  warn "expected 32 lowercase hex characters, got '${R2_ACCOUNT_ID}' — try again"
done
write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "R2 — create bucket ${BUCKET}"
say "One bucket holds everything: manifest.json, manifests/, objects/, redist/, news/, launcher/."
say "The name is baked into publish.config.json, so it must be exactly '${BUCKET}'."
open_url "https://dash.cloudflare.com/?to=/:account/r2/new"
step "Bucket name: ${BUCKET}"
step "Location: leave 'Automatic' (there is no South America hint; the edge cache serves players anyway)."
step "Default storage class: Standard."
step "Click 'Create bucket'."
note "If the bucket already exists from an earlier run, just continue."
warn "Do NOT enable the r2.dev public URL — it is rate-limited and not for players. Stage 4 adds the real domain."
pause "Bucket created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "R2 — API token (Object Read & Write, this bucket only)"
say "The CLI reads R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY from the environment only."
say "They land in ${ENV_FILE} (gitignored) — never in the repo."
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
note "If that link lands elsewhere: R2 Object Storage → Overview → right sidebar → 'Manage R2 API Tokens'."
step "Click 'Create API token' (choose an Account API token if the dashboard offers Account vs User —"
step "  it does not die with a user's membership)."
step "Token name: yufa-publish"
step "Permissions: 'Object Read & Write'  — NOT 'Admin Read & Write'."
step "Specify bucket(s): 'Apply to specific buckets only' → ${BUCKET}"
step "TTL: Forever.  Client IP filtering: leave empty."
step "Click 'Create API Token'."
warn "The next page shows the Access Key ID and Secret Access Key ONCE. Copy both before leaving it."
note "That page also shows the S3 endpoint; it should contain ${R2_ACCOUNT_ID}."
ask R2_ACCESS_KEY_ID "Paste the Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key (hidden):"
if [[ -z "$R2_ACCESS_KEY_ID" || -z "$R2_SECRET_ACCESS_KEY" ]]; then
  warn "empty key — re-run this wizard after creating the token"
  exit 1
fi
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "R2 — custom domain for the bucket"
say "Players and the launcher fetch everything over plain HTTPS from this hostname."
say "It must be a subdomain of a zone that lives on THIS Cloudflare account (e.g. patch.yufa.com.br)."
open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/${BUCKET}/settings"
note "If that link fails: R2 Object Storage → ${BUCKET} → Settings tab."
step "Under 'Public access' → 'Custom Domains' → click 'Add' (or 'Connect Domain')."
step "Enter the hostname, e.g. patch.<your zone>  → Continue → 'Connect domain'."
step "Cloudflare creates the DNS record itself. Wait until Status shows 'Active' (usually < 5 min)."
while :; do
  ask PATCH_DOMAIN "Hostname you connected (e.g. patch.yufa.com.br):"
  [[ "$PATCH_DOMAIN" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]] && break
  warn "that doesn't look like a hostname (lowercase, no scheme, no trailing slash) — try again"
done
write_env PATCH_DOMAIN "$PATCH_DOMAIN"
pause "Status shows Active (or Initializing — stage 7 re-checks)?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Repo — replace REPLACE_WITH_ACCOUNT_ID / REPLACE_WITH_DOMAIN"
say "Three tracked files still carry placeholders (GOLIVE 'Decisão — domínio'):"
for f in "${CONFIG_FILES[@]}"; do note "  - $f"; done
say ""
say "Substitutions:"
note "  REPLACE_WITH_ACCOUNT_ID        → ${R2_ACCOUNT_ID}"
note "  patch.REPLACE_WITH_DOMAIN      → ${PATCH_DOMAIN}"
pending=()
for f in "${CONFIG_FILES[@]}"; do
  grep -qE 'REPLACE_WITH_(ACCOUNT_ID|DOMAIN)' "$f" && pending+=("$f")
done
if (( ${#pending[@]} == 0 )); then
  note "no placeholders left — already substituted on a previous run:"
  grep -nE 'r2\.cloudflarestorage\.com|https://patch\.' "${CONFIG_FILES[@]}" | sed 's/^/    /' || true
else
  if confirm "Edit ${#pending[@]} file(s) in place? (git diff reviews it)"; then
    for f in "${pending[@]}"; do
      sed -i \
        -e "s|REPLACE_WITH_ACCOUNT_ID|${R2_ACCOUNT_ID}|g" \
        -e "s|patch\.REPLACE_WITH_DOMAIN|${PATCH_DOMAIN}|g" \
        "$f"
      printf '  %s✓ edited%s %s\n' "$GREEN" "$RESET" "$f"
    done
    if grep -qE 'REPLACE_WITH_' "${CONFIG_FILES[@]}"; then
      warn "some REPLACE_WITH_ markers survived — inspect by hand:"
      grep -nE 'REPLACE_WITH_' "${CONFIG_FILES[@]}" | sed 's/^/    /' || true
    fi
    say ""
    git --no-pager diff --stat -- "${CONFIG_FILES[@]}" | sed 's/^/  /' || true
  else
    SKIPPED+=("placeholder substitution in: ${pending[*]}")
    warn "skipped — do it by hand before the first release"
  fi
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — Cache Rule: bypass the mutable keys"
say "The CLI already sends Cache-Control: no-cache on mutable keys, but an explicit bypass rule"
say "guarantees a rollback or news push is visible instantly. Immutable keys (objects/, manifests/)"
say "stay cacheable forever."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/caching/cache-rules"
note "Pick the zone that owns ${PATCH_DOMAIN} if the dashboard asks."
step "Click 'Create rule'.  Rule name: yufa-patch bypass mutable"
step "When incoming requests match… → 'Custom filter expression' → 'Edit expression', paste:"
say ""
printf '%s' "$BOLD"
cat <<EXPR
    (http.host eq "${PATCH_DOMAIN}" and (
        http.request.uri.path eq "/manifest.json"
     or starts_with(http.request.uri.path, "/news/")
     or starts_with(http.request.uri.path, "/redist/")
     or http.request.uri.path eq "/launcher/latest.yml"
    ))
EXPR
printf '%s\n' "$RESET"
step "Cache eligibility → 'Bypass cache'.  Leave everything else default."
step "Click 'Deploy'."
pause "Rule 1 deployed?"
say ""
say "Rule 2 — Cloudflare only edge-caches by file extension by default. objects/<sha256> has none,"
say "so without this rule every player download hits R2 origin instead of the edge."
step "'Create rule' again.  Rule name: yufa-patch cache immutable"
step "Custom filter expression → Edit expression, paste:"
say ""
printf '%s' "$BOLD"
cat <<EXPR
    (http.host eq "${PATCH_DOMAIN}" and (
        starts_with(http.request.uri.path, "/objects/")
     or starts_with(http.request.uri.path, "/manifests/")
     or (starts_with(http.request.uri.path, "/launcher/") and http.request.uri.path ne "/launcher/latest.yml")
    ))
EXPR
printf '%s\n' "$RESET"
step "Cache eligibility → 'Eligible for cache'.  Edge TTL: leave default (respects the CLI's"
step "  'public, max-age=31536000, immutable').  Click 'Deploy'."
note "Free plan caches objects up to 512 MB; bigger Blobs just stream from R2 uncached — still fine."
pause "Rule 2 deployed?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify — HTTP Range (206) through ${PATCH_DOMAIN}"
say "Resumable downloads need Range support end-to-end. The bucket is empty until the first"
say "release, so we upload a throwaway 4 KB object, probe it with curl, then delete it."
tmpdir=$(mktemp -d)
{ yes "yufa range test line" || true; } | head -c 4096 > "$tmpdir/rangetest.txt"
winpath="$tmpdir/rangetest.txt"; opendir="$tmpdir"
if command -v cygpath >/dev/null 2>&1; then
  winpath=$(cygpath -w "$tmpdir/rangetest.txt"); opendir=$(cygpath -w "$tmpdir")
fi
say ""
say "Test file:  ${BOLD}${winpath}${RESET}"
open_url "$opendir"
open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/${BUCKET}"
step "On the bucket's Objects tab click 'Upload' and drop rangetest.txt (keep the name, no prefix)."
pause "Uploaded?"

url="https://${PATCH_DOMAIN}/rangetest.txt"
while :; do
  code=$(curl -r 0-1023 -s -o /dev/null -w '%{http_code}' "$url") || code="000"
  cache=$(curl -r 0-1023 -sI "$url" | tr -d '\r' | awk -F': ' 'tolower($1)=="cf-cache-status"{print $2}') || cache=""
  if [[ "$code" == "206" ]]; then
    printf '  %s✓ %s → 206 Partial Content%s  (cf-cache-status: %s)\n' "$GREEN" "$url" "$RESET" "${cache:-n/a}"
    break
  fi
  warn "$url → HTTP $code (cf-cache-status: ${cache:-n/a}); expected 206"
  note "000 = DNS/TLS not ready yet (domain still Initializing). 404 = wrong key/prefix. 200 = Range ignored."
  confirm "Retry?" || { SKIPPED+=("Range check on $url returned $code — re-run GOLIVE step 1 curl after first release"); break; }
done

mhead=$(curl -sI "https://${PATCH_DOMAIN}/manifest.json" | tr -d '\r') || mhead=""
mcode=$(printf '%s\n' "$mhead" | awk 'NR==1{print $2}')
mcache=$(printf '%s\n' "$mhead" | awk -F': ' 'tolower($1)=="cf-cache-status"{print $2}')
note "manifest.json (not published yet) → HTTP ${mcode:-?}, cf-cache-status: ${mcache:-n/a}  (BYPASS = stage 6 rule matches)"
say ""
step "Back in the dashboard, delete rangetest.txt from the bucket."
pause "Deleted?"
rm -rf "$tmpdir"

# ──────────────────────────────────────────────────────────────────────────
finish
say "Load ${ENV_FILE} into the shell before publishing (nothing reads .env automatically):"
say ""
note "  PowerShell:  Get-Content .env | ? { \$_ -match '^[^#].*=' } | % { \$k,\$v = \$_ -split '=',2; Set-Item \"env:\$k\" \$v }"
note "  bash:        set -a; . ./.env; set +a"
say ""
say "Then GOLIVE step 3:"
note "  npm run yufa-publish -- --dry-run release --dir \"C:\\tree of savior servers\\ClassicV1.0\" --label 1.0"
say ""
